# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "mable_left", "mable_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# https://github.com/slicemk/zmk/tree/main/app/boards/arm/raytac_mdbt50q_rx
---
include:
  - board: raytac_mdbt50q_rx
    shield: mable_dongle
  - board: seeeduino_xiao_ble
    shield: mable_left
  - board: seeeduino_xiao_ble
    shield: mable_right
  - board: raytac_mdbt50q_rx
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
